export const DASHBOARD_NAVI_REQUESTED = 'DASHBOARD_NAVI_REQUESTED';
export const DASHBOARD_NAVI__SUCCEEDED = 'DASHBOARD_NAVI__SUCCEEDED';
export const DASHBOARD_NAVI__FAILED = 'DASHBOARD_NAVI__FAILED';

export const HTML_FETCH_REQUESTED = 'HTML_FETCH_REQUESTED';
export const HTML_FETCH__SUCCEEDED = 'HTML_FETCH__SUCCEEDED';
export const HTML_FETCH__FAILED = 'HTML_FETCH__FAILED';

export const SEARCH_BAR_TOGGLE_REQUESTED = 'SEARCH_BAR_TOGGLE_REQUESTED';
export const SEARCH_BAR_TOGGLE__SUCCEEDED = 'SEARCH_BAR_TOGGLE__SUCCEEDED';
export const SEARCH_BAR_TOGGLE__FAILED = 'SEARCH_BAR_TOGGLE__FAILED';

export const TAB_BAR_UPDATE_REQUESTED = 'TAB_BAR_UPDATE_REQUESTED';
export const TAB_BAR_UPDATE__SUCCEEDED = 'TAB_BAR_UPDATE__SUCCEEDED';
export const TAB_BAR_UPDATE__FAILED = 'TAB_BAR_UPDATE__FAILED';

export const CHANNEL_UPDATE_SEARCH_REQUESTED =
  'CHANNEL_UPDATE_SEARCH_REQUESTED';
export const CHANNEL_UPDATE_SEARCH__SUCCEEDED =
  'CHANNEL_UPDATE_SEARCH__SUCCEEDED';
export const CHANNEL_UPDATE_SEARCH__FAILED = 'CHANNEL_UPDATE_SEARCH__FAILED';

export const CHANNEL_UPDATE_FILTER_REQUESTED =
  'CHANNEL_UPDATE_FILTER_REQUESTED';
export const CHANNEL_UPDATE_FILTER__SUCCEEDED =
  'CHANNEL_UPDATE_FILTER__SUCCEEDED';
export const CHANNEL_UPDATE_FILTER__FAILED = 'CHANNEL_UPDATE_FILTER__FAILED';

export const CHANNEL_CLEAR_FILTER_REQUESTED = 'CHANNEL_CLEAR_FILTER_REQUESTED';
export const CHANNEL_CLEAR_FILTER__SUCCEEDED =
  'CHANNEL_CLEAR_FILTER__SUCCEEDED';
export const CHANNEL_CLEAR_FILTER__FAILED = 'CHANNEL_CLEAR_FILTER__FAILED';

export const CHANNEL_FETCH_REQUESTED = 'CHANNEL_FETCH_REQUESTED';
export const CHANNEL_FETCH__SUCCEEDED = 'CHANNEL_FETCH__SUCCEEDED';
export const CHANNEL_FETCH__FAILED = 'CHANNEL_FETCH__FAILED';

export const CHANNEL_UPDATE_STATUS_REQUESTED =
  'CHANNEL_UPDATE_STATUS_REQUESTED';
export const CHANNEL_UPDATE_STATUS__SUCCEEDED =
  'CHANNEL_UPDATE_STATUS__SUCCEEDED';
export const CHANNEL_UPDATE_STATUS__FAILED = 'CHANNEL_UPDATE_STATUS__FAILED';

export const CHANNEL_DELETE_REQUESTED = 'CHANNEL_DELETE_REQUESTED';
export const CHANNEL_DELETE__SUCCEEDED = 'CHANNEL_DELETE__SUCCEEDED';
export const CHANNEL_DELETE__FAILED = 'CHANNEL_DELETE__FAILED';

export const EXPERIENCE_UPDATE_SEARCH_REQUESTED =
  'EXPERIENCE_UPDATE_SEARCH_REQUESTED';
export const EXPERIENCE_UPDATE_SEARCH__SUCCEEDED =
  'EXPERIENCE_UPDATE_SEARCH__SUCCEEDED';
export const EXPERIENCE_UPDATE_SEARCH__FAILED =
  'EXPERIENCE_UPDATE_SEARCH__FAILED';

export const EXPERIENCE_UPDATE_FILTER_REQUESTED =
  'EXPERIENCE_UPDATE_FILTER_REQUESTED';
export const EXPERIENCE_UPDATE_FILTER__SUCCEEDED =
  'EXPERIENCE_UPDATE_FILTER__SUCCEEDED';
export const EXPERIENCE_UPDATE_FILTER__FAILED =
  'EXPERIENCE_UPDATE_FILTER__FAILED';

export const EXPERIENCE_CLEAR_FILTER_REQUESTED =
  'EXPERIENCE_CLEAR_FILTER_REQUESTED';
export const EXPERIENCE_CLEAR_FILTER__SUCCEEDED =
  'EXPERIENCE_CLEAR_FILTER__SUCCEEDED';
export const EXPERIENCE_CLEAR_FILTER__FAILED =
  'EXPERIENCE_CLEAR_FILTER__FAILED';

export const EXPERIENCE_FETCH_REQUESTED = 'EXPERIENCE_FETCH_REQUESTED';
export const EXPERIENCE_FETCH__SUCCEEDED = 'EXPERIENCE_FETCH__SUCCEEDED';
export const EXPERIENCE_FETCH__FAILED = 'EXPERIENCE_FETCH__FAILED';

export const EXPERIENCE_FETCH_MORE_REQUESTED =
  'EXPERIENCE_FETCH_MORE_REQUESTED';
export const EXPERIENCE_FETCH_MORE__SUCCEEDED =
  'EXPERIENCE_FETCH_MORE__SUCCEEDED';
export const EXPERIENCE_FETCH_MORE__FAILED = 'EXPERIENCE_FETCH_MORE__FAILED';

export const EXPERIENCE_DELETE_REQUESTED = 'EXPERIENCE_DELETE_REQUESTED';
export const EXPERIENCE_DELETE__SUCCEEDED = 'EXPERIENCE_DELETE__SUCCEEDED';
export const EXPERIENCE_DELETE__FAILED = 'EXPERIENCE_DELETE__FAILED';

export const STREAM_SEARCH_BAR_TOGGLE_REQUESTED =
  'STREAM_SEARCH_BAR_TOGGLE_REQUESTED';
export const STREAM_SEARCH_BAR_TOGGLE__SUCCEEDED =
  'STREAM_SEARCH_BAR_TOGGLE__SUCCEEDED';
export const STREAM_SEARCH_BAR_TOGGLE__FAILED =
  'STREAM_SEARCH_BAR_TOGGLE__FAILED';

export const STREAM_TAB_BAR_UPDATE_REQUESTED =
  'STREAM_TAB_BAR_UPDATE_REQUESTED';
export const STREAM_TAB_BAR_UPDATE__SUCCEEDED =
  'STREAM_TAB_BAR_UPDATE__SUCCEEDED';
export const STREAM_TAB_BAR_UPDATE__FAILED = 'STREAM_TAB_BAR_UPDATE__FAILED';

export const STREAM_CHANNEL_LANGUAGES_FETCH_REQUESTED =
  'STREAM_CHANNEL_LANGUAGES_FETCH_REQUESTED';
export const STREAM_CHANNEL_LANGUAGES_FETCH__SUCCEEDED =
  'STREAM_CHANNEL_LANGUAGES_FETCH__SUCCEEDED';
export const STREAM_CHANNEL_LANGUAGES_FETCH__FAILED =
  'STREAM_CHANNEL_LANGUAGES_FETCH__FAILED';

export const STREAM_CHANNEL_LANGUAGES_UPDATE_FILTER_REQUESTED =
  'STREAM_CHANNEL_LANGUAGES_UPDATE_FILTER_REQUESTED';
export const STREAM_CHANNEL_LANGUAGES_UPDATE_FILTER__SUCCEEDED =
  'STREAM_CHANNEL_LANGUAGES_UPDATE_FILTER__SUCCEEDED';
export const STREAM_CHANNEL_LANGUAGES_UPDATE_FILTER__FAILED =
  'STREAM_CHANNEL_LANGUAGES_UPDATE_FILTER__FAILED';

export const STREAM_CHANNEL_FETCH_REQUESTED = 'STREAM_CHANNEL_FETCH_REQUESTED';
export const STREAM_CHANNEL_FETCH__SUCCEEDED =
  'STREAM_CHANNEL_FETCH__SUCCEEDED';
export const STREAM_CHANNEL_FETCH__FAILED = 'STREAM_CHANNEL_FETCH__FAILED';

export const STREAM_FETCH_MORE_CHANNEL_REQUESTED =
  'STREAM_FETCH_MORE_CHANNEL_REQUESTED';
export const STREAM_FETCH_MORE_CHANNEL__SUCCEEDED =
  'STREAM_FETCH_MORE_CHANNEL__SUCCEEDED';
export const STREAM_FETCH_MORE_CHANNEL__FAILED =
  'STREAM_FETCH_MORE_CHANNEL__FAILED';

export const STREAM_CHANNEL_UPDATE_SEARCH_REQUESTED =
  'STREAM_CHANNEL_UPDATE_SEARCH_REQUESTED';
export const STREAM_CHANNEL_UPDATE_SEARCH__SUCCEEDED =
  'STREAM_CHANNEL_UPDATE_SEARCH__SUCCEEDED';
export const STREAM_CHANNEL_UPDATE_SEARCH__FAILED =
  'STREAM_CHANNEL_UPDATE_SEARCH__FAILED';

export const STREAM_CHANNEL_UPDATE_FILTER_REQUESTED =
  'STREAM_CHANNEL_UPDATE_FILTER_REQUESTED';
export const STREAM_CHANNEL_UPDATE_FILTER__SUCCEEDED =
  'STREAM_CHANNEL_UPDATE_FILTER__SUCCEEDED';
export const STREAM_CHANNEL_UPDATE_FILTER__FAILED =
  'STREAM_CHANNEL_UPDATE_FILTER__FAILED';

export const STREAM_CHANNEL_CLEAR_FILTER_REQUESTED =
  'STREAM_CHANNEL_CLEAR_FILTER_REQUESTED';
export const STREAM_CHANNEL_CLEAR_FILTER__SUCCEEDED =
  'STREAM_CHANNEL_CLEAR_FILTER__SUCCEEDED';
export const STREAM_CHANNEL_CLEAR_FILTER__FAILED =
  'STREAM_CHANNEL_CLEAR_FILTER__FAILED';

export const STREAM_CHANNEL_SELECT_REQUESTED =
  'STREAM_CHANNEL_SELECT_REQUESTED';
export const STREAM_CHANNEL_SELECT__SUCCEEDED =
  'STREAM_CHANNEL_SELECT__SUCCEEDED';
export const STREAM_CHANNEL_SELECT__FAILED = 'STREAM_CHANNEL_SELECT__FAILED';

export const STREAM_CREATE_REQUESTED = 'STREAM_CREATE_REQUESTED';
export const STREAM_CREATE__SUCCEEDED = 'STREAM_CREATE__SUCCEEDED';
export const STREAM_CREATE__FAILED = 'STREAM_CREATE__FAILED';

export const STREAM_REMOVE_REQUESTED = 'STREAM_REMOVE_REQUESTED';
export const STREAM_REMOVE__SUCCEEDED = 'STREAM_REMOVE__SUCCEEDED';
export const STREAM_REMOVE__FAILED = 'STREAM_REMOVE__FAILED';

export const STREAM_FETCH_MORE_EXPERIENCE_REQUESTED =
  'STREAM_FETCH_MORE_EXPERIENCE_REQUESTED';
export const STREAM_FETCH_MORE_EXPERIENCE__SUCCEEDED =
  'STREAM_FETCH_MORE_EXPERIENCE__SUCCEEDED';
export const STREAM_FETCH_MORE_EXPERIENCE__FAILED =
  'STREAM_FETCH_MORE_EXPERIENCE__FAILED';

export const STREAM_FETCH_MORE_STREAM_REQUESTED =
  'STREAM_FETCH_MORE_STREAM_REQUESTED';
export const STREAM_FETCH_MORE_STREAM__SUCCEEDED =
  'STREAM_FETCH_MORE_STREAM__SUCCEEDED';
export const STREAM_FETCH_MORE_STREAM__FAILED =
  'STREAM_FETCH_MORE_STREAM__FAILED';

export const STREAM_UPDATE_SEARCH_REQUESTED = 'STREAM_UPDATE_SEARCH_REQUESTED';
export const STREAM_UPDATE_SEARCH__SUCCEEDED =
  'STREAM_UPDATE_SEARCH__SUCCEEDED';
export const STREAM_UPDATE_SEARCH__FAILED = 'STREAM_UPDATE_SEARCH__FAILED';

export const USER_UPDATE_INFO_SEARCH_REQUESTED =
  'USER_UPDATE_INFO_SEARCH_REQUESTED';
export const USER_UPDATE_INFO_SEARCH__SUCCEEDED =
  'USER_UPDATE_INFO_SEARCH__SUCCEEDED';
export const USER_UPDATE_INFO_SEARCH__FAILED =
  'USER_UPDATE_INFO_SEARCH__FAILED';

export const USER_UPDATE_CHANNEL_SEARCH_REQUESTED =
  'USER_UPDATE_CHANNEL_SEARCH_REQUESTED';
export const USER_UPDATE_CHANNEL_SEARCH__SUCCEEDED =
  'USER_UPDATE_CHANNEL_SEARCH__SUCCEEDED';
export const USER_UPDATE_CHANNEL_SEARCH__FAILED =
  'USER_UPDATE_CHANNEL_SEARCH__FAILED';

export const USER_UPDATE_CHANNEL_SELECT_REQUEST =
  'USER_UPDATE_CHANNEL_SELECT_REQUEST';
export const USER_UPDATE_CHANNEL_SELECT__SUCCEEDED =
  'USER_UPDATE_CHANNEL_SELECT__SUCCEEDED';
export const USER_UPDATE_CHANNEL_SELECT__FAILED =
  'USER_UPDATE_CHANNEL_SELECT__FAILED';

export const USER_UPDATE_PAGE_LIMIT_SELECT_REQUEST =
  'USER_UPDATE_PAGE_LIMIT_SELECT_REQUEST';
export const USER_UPDATE_PAGE_LIMIT_SELECT__SUCCEEDED =
  'USER_UPDATE_PAGE_LIMIT_SELECT__SUCCEEDED';
export const USER_UPDATE_PAGE_LIMIT_SELECT__FAILED =
  'USER_UPDATE_PAGE_LIMIT_SELECT__FAILED';

export const USER_UPDATE_PAGE_INDEX_REQUEST = 'USER_UPDATE_PAGE_INDEX_REQUEST';
export const USER_UPDATE_PAGE_INDEX__SUCCEEDED =
  'USER_UPDATE_PAGE_INDEX__SUCCEEDED';
export const USER_UPDATE_PAGE_INDEX__FAILED = 'USER_UPDATE_PAGE_INDEX__FAILED';

export const USER_TOGGLE_INVITE_MODAL = 'USER_TOGGLE_INVITE_MODAL';

export const USER_UPDATE_NEW_USER_REQUEST = 'USER_UPDATE_NEW_USER_REQUEST';
export const USER_UPDATE_NEW_USER__SUCCEEDED =
  'USER_UPDATE_NEW_USER__SUCCEEDED';
export const USER_UPDATE_NEW_USER__FAILED = 'USER_UPDATE_NEW_USER__FAILED';

export const USER_BLUR_NEW_USER_EMAIL = 'USER_BLUR_NEW_USER_EMAIL';

export const USER_ADD_NEW_USER_FORM = 'USER_ADD_NEW_USER_FORM';

export const USER_DELETE_NEW_USER_FORM = 'USER_DELETE_NEW_USER_FORM';

export const USER_UPDATE_NEW_USER_CHANNEL_SEARCH_REQUESTED =
  'USER_UPDATE_NEW_USER_CHANNEL_SEARCH_REQUESTED';
export const USER_UPDATE_NEW_USER_CHANNEL_SEARCH__SUCCEEDED =
  'USER_UPDATE_NEW_USER_CHANNEL_SEARCH__SUCCEEDED';
export const USER_UPDATE_NEW_USER_CHANNEL_SEARCH__FAILED =
  'USER_UPDATE_NEW_USER_CHANNEL_SEARCH__FAILED';

export const USER_UPDATE_NEW_USER_CHANNEL_SELECT =
  'USER_UPDATE_NEW_USER_CHANNEL_SELECT';

export const USER_UPDATE_NEW_USER_CREATE_REQUESTED =
  'USER_UPDATE_NEW_USER_CREATE_REQUESTED';
export const USER_UPDATE_NEW_USER_CREATE__SUCCEEDED =
  'USER_UPDATE_NEW_USER_CREATE__SUCCEEDED';
export const USER_UPDATE_NEW_USER_CREATE__FAILED =
  'USER_UPDATE_NEW_USER_CREATE__FAILED';

export const USER_FETCH_USER_VIEW_REQUESTED = 'USER_FETCH_USER_VIEW_REQUESTED';
export const USER_FETCH_USER_VIEW__SUCCEEDED =
  'USER_FETCH_USER_VIEW__SUCCEEDED';
export const USER_FETCH_USER_VIEW__FAILED = 'USER_FETCH_USER_VIEW__FAILED';

export const USER_UPDATE_USER_INPUT_REQUESTED =
  'USER_UPDATE_USER_INPUT_REQUESTED';
export const USER_UPDATE_USER_INPUT__SUCCEEDED =
  'USER_UPDATE_USER_INPUT__SUCCEEDED';
export const USER_UPDATE_USER_INPUT__FAILED = 'USER_UPDATE_USER_INPUT__FAILED';

export const USER_UPDATE_USER_ENABLE = 'USER_UPDATE_USER_ENABLE';

export const USER_UPDATE_EDIT_USER_CHANNEL_SEARCH_REQUESTED =
  'USER_UPDATE_EDIT_USER_CHANNEL_SEARCH_REQUESTED';
export const USER_UPDATE_EDIT_USER_CHANNEL_SEARCH__SUCCEEDED =
  'USER_UPDATE_EDIT_USER_CHANNEL_SEARCH__SUCCEEDED';
export const USER_UPDATE_EDIT_USER_CHANNEL_SEARCH__FAILED =
  'USER_UPDATE_EDIT_USER_CHANNEL_SEARCH__FAILED';

export const USER_UPDATE_EDIT_USER_CHANNEL_SELECT =
  'USER_UPDATE_EDIT_USER_CHANNEL_SELECT';

export const USER_UPDATE_USER_REQUESTED = 'USER_UPDATE_USER_REQUESTED';
export const USER_UPDATE_USER__SUCCEEDED = 'USER_UPDATE_USER__SUCCEEDED';
export const USER_UPDATE_USER__FAILED = 'USER_UPDATE_USER__FAILED';

export const USER_DELETE_USER_REQUESTED = 'USER_DELETE_USER_REQUESTED';
export const USER_DELETE_USER__SUCCEEDED = 'USER_DELETE_USER__SUCCEEDED';
export const USER_DELETE_USER__FAILED = 'USER_DELETE_USER__FAILED';

export const USER_BLUR_USER_EMAIL = 'USER_BLUR_USER_EMAIL';

export const USER_TOGGLE_USER_PASSWORD_MODAL =
  'USER_TOGGLE_USER_PASSWORD_MODAL';

export const USER_RESET_PASSWORD_REQUEST = 'USER_RESET_PASSWORD_REQUEST';
export const USER_RESET_PASSWORD__SUCCEEDED = 'USER_RESET_PASSWORD__SUCCEEDED';
export const USER_RESET_PASSWORD__FAILED = 'USER_RESET_PASSWORD__FAILED';

export const USER_TOGGLE_USER_DELETE_MODAL = 'USER_TOGGLE_USER_DELETE_MODAL';

// SELECT ACTIONS
export const USER_UPDATE_SELECT_MODE = 'USER_UPDATE_SELECT_MODE';
export const USER_TOGGLE_USER_SELECT = 'USER_TOGGLE_USER_SELECT';
export const USER_TOGGLE_USER_SELECT_ALL = 'USER_TOGGLE_USER_SELECT_ALL';

// Grant access
export const USER_TOGGLE_GRANT_ACCESS_MODAL = 'USER_TOGGLE_GRANT_ACCESS_MODAL';

export const USER_UPDATE_SELECTED_USER_CHANNEL_SEARCH_REQUESTED =
  'USER_UPDATE_SELECTED_USER_CHANNEL_SEARCH_REQUESTED';
export const USER_UPDATE_SELECTED_USER_CHANNEL_SEARCH__SUCCEEDED =
  'USER_UPDATE_SELECTED_USER_CHANNEL_SEARCH__SUCCEEDED';
export const USER_UPDATE_SELECTED_USER_CHANNEL_SEARCH__FAILED =
  'USER_UPDATE_SELECTED_USER_CHANNEL_SEARCH__FAILED';

export const USER_UPDATE_SELECTED_USER_CHANNEL_SELECT =
  'USER_UPDATE_SELECTED_USER_CHANNEL_SELECT';

export const USER_UPDATE_SELECTED_USER_GRANT_ACCESS_REQUESTED =
  'USER_UPDATE_SELECTED_USER_GRANT_ACCESS_REQUESTED';
export const USER_UPDATE_SELECTED_USER_GRANT_ACCESS__SUCCEEDED =
  'USER_UPDATE_SELECTED_USER_GRANT_ACCESS__SUCCEEDED';
export const USER_UPDATE_SELECTED_USER_GRANT_ACCESS__FAILED =
  'USER_UPDATE_SELECTED_USER_GRANT_ACCESS__FAILED';

// Remove access
export const USER_TOGGLE_REMOVE_ACCESS_MODAL =
  'USER_TOGGLE_REMOVE_ACCESS_MODAL';

// Lock
export const USER_TOGGLE_USERS_LOCK_MODAL = 'USER_TOGGLE_USERS_LOCK_MODAL';

export const USER_TOGGLE_USERS_LOCK_REQUESTED =
  'USER_TOGGLE_USERS_LOCK_REQUESTED';
export const USER_TOGGLE_USERS_LOCK__SUCCEEDED =
  'USER_TOGGLE_USERS_LOCK__SUCCEEDED';
export const USER_TOGGLE_USERS_LOCK__FAILED = 'USER_TOGGLE_USERS_LOCK__FAILED';

// Delete
export const USER_TOGGLE_DELETE_USERS_MODAL = 'USER_TOGGLE_DELETE_USERS_MODAL';

export const USER_TOGGLE_DELETE_USERS_REQUESTED =
  'USER_TOGGLE_DELETE_USERS_REQUESTED';
export const USER_TOGGLE_DELETE_USERS__SUCCEEDED =
  'USER_TOGGLE_DELETE_USERS__SUCCEEDED';
export const USER_TOGGLE_DELETE_USERS__FAILED =
  'USER_TOGGLE_DELETE_USERS__FAILED';
