export const MEMBER_UPDATE_INFO_SEARCH_REQUESTED =
  'MEMBER_UPDATE_INFO_SEARCH_REQUESTED';
export const MEMBER_UPDATE_INFO_SEARCH__SUCCEEDED =
  'MEMBER_UPDATE_INFO_SEARCH__SUCCEEDED';
export const MEMBER_UPDATE_INFO_SEARCH__FAILED =
  'MEMBER_UPDATE_INFO_SEARCH__FAILED';

export const MEMBER_UPDATE_PAGE_INDEX_REQUEST =
  'MEMBER_UPDATE_PAGE_INDEX_REQUEST';
export const MEMBER_UPDATE_PAGE_INDEX__SUCCEEDED =
  'MEMBER_UPDATE_PAGE_INDEX__SUCCEEDED';
export const MEMBER_UPDATE_PAGE_INDEX__FAILED =
  'MEMBER_UPDATE_PAGE_INDEX__FAILED';

export const MEMBER_TOGGLE_INVITE_MODAL = 'MEMBER_TOGGLE_INVITE_MODAL';

export const MEMBER_UPDATE_NEW_MEMBER_REQUEST =
  'MEMBER_UPDATE_NEW_MEMBER_REQUEST';
export const MEMBER_UPDATE_NEW_MEMBER__SUCCEEDED =
  'MEMBER_UPDATE_NEW_MEMBER__SUCCEEDED';
export const MEMBER_UPDATE_NEW_MEMBER__FAILED =
  'MEMBER_UPDATE_NEW_MEMBER__FAILED';

export const MEMBER_BLUR_NEW_MEMBER_EMAIL = 'MEMBER_BLUR_NEW_MEMBER_EMAIL';

export const MEMBER_ADD_NEW_MEMBER_FORM = 'MEMBER_ADD_NEW_MEMBER_FORM';

export const MEMBER_DELETE_NEW_MEMBER_FORM = 'MEMBER_DELETE_NEW_MEMBER_FORM';

export const MEMBER_UPDATE_NEW_MEMBER_CHANNEL_SEARCH_REQUESTED =
  'MEMBER_UPDATE_NEW_MEMBER_CHANNEL_SEARCH_REQUESTED';
export const MEMBER_UPDATE_NEW_MEMBER_CHANNEL_SEARCH__SUCCEEDED =
  'MEMBER_UPDATE_NEW_MEMBER_CHANNEL_SEARCH__SUCCEEDED';
export const MEMBER_UPDATE_NEW_MEMBER_CHANNEL_SEARCH__FAILED =
  'MEMBER_UPDATE_NEW_MEMBER_CHANNEL_SEARCH__FAILED';

export const MEMBER_UPDATE_NEW_MEMBER_ROLE_SELECT =
  'MEMBER_UPDATE_NEW_MEMBER_ROLE_SELECT';

export const MEMBER_UPDATE_NEW_MEMBER_CREATE_REQUESTED =
  'MEMBER_UPDATE_NEW_MEMBER_CREATE_REQUESTED';
export const MEMBER_UPDATE_NEW_MEMBER_CREATE__SUCCEEDED =
  'MEMBER_UPDATE_NEW_MEMBER_CREATE__SUCCEEDED';
export const MEMBER_UPDATE_NEW_MEMBER_CREATE__FAILED =
  'MEMBER_UPDATE_NEW_MEMBER_CREATE__FAILED';

export const MEMBER_FETCH_MEMBER_VIEW_REQUESTED =
  'MEMBER_FETCH_MEMBER_VIEW_REQUESTED';
export const MEMBER_FETCH_MEMBER_VIEW__SUCCEEDED =
  'MEMBER_FETCH_MEMBER_VIEW__SUCCEEDED';
export const MEMBER_FETCH_MEMBER_VIEW__FAILED =
  'MEMBER_FETCH_MEMBER_VIEW__FAILED';

export const MEMBER_UPDATE_MEMBER_INPUT_REQUESTED =
  'MEMBER_UPDATE_MEMBER_INPUT_REQUESTED';
export const MEMBER_UPDATE_MEMBER_INPUT__SUCCEEDED =
  'MEMBER_UPDATE_MEMBER_INPUT__SUCCEEDED';
export const MEMBER_UPDATE_MEMBER_INPUT__FAILED =
  'MEMBER_UPDATE_MEMBER_INPUT__FAILED';

export const MEMBER_UPDATE_MEMBER_ENABLE = 'MEMBER_UPDATE_MEMBER_ENABLE';

export const MEMBER_UPDATE_EDIT_MEMBER_ROLE_SELECT =
  'MEMBER_UPDATE_EDIT_MEMBER_ROLE_SELECT';

export const MEMBER_UPDATE_MEMBER_REQUESTED = 'MEMBER_UPDATE_MEMBER_REQUESTED';
export const MEMBER_UPDATE_MEMBER__SUCCEEDED =
  'MEMBER_UPDATE_MEMBER__SUCCEEDED';
export const MEMBER_UPDATE_MEMBER__FAILED = 'MEMBER_UPDATE_MEMBER__FAILED';

export const MEMBER_DELETE_MEMBER_REQUESTED = 'MEMBER_DELETE_MEMBER_REQUESTED';
export const MEMBER_DELETE_MEMBER__SUCCEEDED =
  'MEMBER_DELETE_MEMBER__SUCCEEDED';
export const MEMBER_DELETE_MEMBER__FAILED = 'MEMBER_DELETE_MEMBER__FAILED';

export const MEMBER_BLUR_MEMBER_EMAIL = 'MEMBER_BLUR_MEMBER_EMAIL';

export const MEMBER_TOGGLE_MEMBER_PASSWORD_MODAL =
  'MEMBER_TOGGLE_MEMBER_PASSWORD_MODAL';

export const MEMBER_RESET_PASSWORD_REQUEST = 'MEMBER_RESET_PASSWORD_REQUEST';
export const MEMBER_RESET_PASSWORD__SUCCEEDED =
  'MEMBER_RESET_PASSWORD__SUCCEEDED';
export const MEMBER_RESET_PASSWORD__FAILED = 'MEMBER_RESET_PASSWORD__FAILED';

export const MEMBER_TOGGLE_MEMBER_DELETE_MODAL =
  'MEMBER_TOGGLE_MEMBER_DELETE_MODAL';

// SELECT ACTIONS
export const MEMBER_UPDATE_SELECT_MODE = 'MEMBER_UPDATE_SELECT_MODE';
export const MEMBER_TOGGLE_MEMBER_SELECT = 'MEMBER_TOGGLE_MEMBER_SELECT';
export const MEMBER_TOGGLE_MEMBER_SELECT_ALL =
  'MEMBER_TOGGLE_MEMBER_SELECT_ALL';

// Grant access
export const MEMBER_TOGGLE_GRANT_ACCESS_MODAL =
  'MEMBER_TOGGLE_GRANT_ACCESS_MODAL';

export const MEMBER_UPDATE_SELECTED_MEMBER_ROLE_SELECT =
  'MEMBER_UPDATE_SELECTED_MEMBER_ROLE_SELECT';

export const MEMBER_UPDATE_SELECTED_MEMBER_GRANT_ACCESS_REQUESTED =
  'MEMBER_UPDATE_SELECTED_MEMBER_GRANT_ACCESS_REQUESTED';
export const MEMBER_UPDATE_SELECTED_MEMBER_GRANT_ACCESS__SUCCEEDED =
  'MEMBER_UPDATE_SELECTED_MEMBER_GRANT_ACCESS__SUCCEEDED';
export const MEMBER_UPDATE_SELECTED_MEMBER_GRANT_ACCESS__FAILED =
  'MEMBER_UPDATE_SELECTED_MEMBER_GRANT_ACCESS__FAILED';

// Remove access
export const MEMBER_TOGGLE_REMOVE_ACCESS_MODAL =
  'MEMBER_TOGGLE_REMOVE_ACCESS_MODAL';

// Lock
export const MEMBER_TOGGLE_MEMBERS_LOCK_MODAL =
  'MEMBER_TOGGLE_MEMBERS_LOCK_MODAL';

export const MEMBER_TOGGLE_MEMBERS_LOCK_REQUESTED =
  'MEMBER_TOGGLE_MEMBERS_LOCK_REQUESTED';
export const MEMBER_TOGGLE_MEMBERS_LOCK__SUCCEEDED =
  'MEMBER_TOGGLE_MEMBERS_LOCK__SUCCEEDED';
export const MEMBER_TOGGLE_MEMBERS_LOCK__FAILED =
  'MEMBER_TOGGLE_MEMBERS_LOCK__FAILED';

// Delete
export const MEMBER_TOGGLE_DELETE_MEMBERS_MODAL =
  'MEMBER_TOGGLE_DELETE_MEMBERS_MODAL';

export const MEMBER_TOGGLE_DELETE_MEMBERS_REQUESTED =
  'MEMBER_TOGGLE_DELETE_MEMBERS_REQUESTED';
export const MEMBER_TOGGLE_DELETE_MEMBERS__SUCCEEDED =
  'MEMBER_TOGGLE_DELETE_MEMBERS__SUCCEEDED';
export const MEMBER_TOGGLE_DELETE_MEMBERS__FAILED =
  'MEMBER_TOGGLE_DELETE_MEMBERS__FAILED';
