export const CHANNEL_TYPE_REQUESTED = 'CHANNEL_TYPE_REQUESTED';
export const CHANNEL_TYPE__SUCCEEDED = 'CHANNEL_TYPE__SUCCEEDED';
export const CHANNEL_TYPE__FAILED = 'CHANNEL_TYPE__FAILED';

export const CHANNEL_VALUE_REQUESTED = 'CHANNEL_VALUE_REQUESTED';
export const CHANNEL_VALUE__SUCCEEDED = 'CHANNEL_VALUE__SUCCEEDED';
export const CHANNEL_VALUE__FAILED = 'CHANNEL_VALUE__FAILED';

export const CHANNEL_CODE_VALUE_REQUESTED = 'CHANNEL_CODE_VALUE_REQUESTED';
export const CHANNEL_CODE_VALUE__SUCCEEDED = 'CHANNEL_CODE_VALUE__SUCCEEDED';
export const CHANNEL_CODE_VALUE__FAILED = 'CHANNEL_CODE_VALUE__FAILED';

export const CHANNEL_CREATE_REQUESTED = 'CHANNEL_CREATE_REQUESTED';
export const CHANNEL_CREATE__SUCCEEDED = 'CHANNEL_CREATE__SUCCEEDED';
export const CHANNEL_CREATE__FAILED = 'CHANNEL_CREATE__FAILED';

export const CHANNEL_VIEW_REQUESTED = 'CHANNEL_VIEW_REQUESTED';
export const CHANNEL_VIEW__SUCCEEDED = 'CHANNEL_VIEW__SUCCEEDED';
export const CHANNEL_VIEW__FAILED = 'CHANNEL_VIEW__FAILED';

export const CHANNEL_UPDATE_REQUESTED = 'CHANNEL_UPDATE_REQUESTED';
export const CHANNEL_UPDATE__SUCCEEDED = 'CHANNEL_UPDATE__SUCCEEDED';
export const CHANNEL_UPDATE__FAILED = 'CHANNEL_UPDATE__FAILED';

export const CHANNEL_FETCH_LANGUAGE_LIST_REQUESTED =
  'CHANNEL_FETCH_LANGUAGE_LIST_REQUESTED';
export const CHANNEL_FETCH_LANGUAGE_LIST__SUCCEEDED =
  'CHANNEL_FETCH_LANGUAGE_LIST__SUCCEEDED';
export const CHANNEL_FETCH_LANGUAGE_LIST__FAILED =
  'CHANNEL_FETCH_LANGUAGE_LIST__FAILED';

export const CHANNEL_SELECT_LANGUAGE_REQUESTED =
  'CHANNEL_SELECT_LANGUAGE_REQUESTED';
