export const ADMIN_TOGGLE_ORG_MODAL = 'ADMIN_TOGGLE_ORG_MODAL';

export const ADMIN_UPDATE_ORG_INPUT = 'ADMIN_UPDATE_ORG_INPUT';

export const ADMIN_FETCH_ORG_LIST_REQUESTED = 'ADMIN_FETCH_ORG_LIST_REQUESTED';
export const ADMIN_FETCH_ORG_LIST__SUCCEEDED =
  'ADMIN_FETCH_ORG_LIST__SUCCEEDED';
export const ADMIN_FETCH_ORG_LIST__FAILED = 'ADMIN_FETCH_ORG_LIST__FAILED';

export const ADMIN_CREATE_ORG_REQUESTED = 'ADMIN_CREATE_ORG_REQUESTED';
export const ADMIN_CREATE_ORG__SUCCEEDED = 'ADMIN_CREATE_ORG__SUCCEEDED';
export const ADMIN_CREATE_ORG__FAILED = 'ADMIN_CREATE_ORG__FAILED';

export const ADMIN_VIEW_ORG_REQUESTED = 'ADMIN_VIEW_ORG_REQUESTED';
export const ADMIN_VIEW_ORG__SUCCEEDED = 'ADMIN_VIEW_ORG__SUCCEEDED';
export const ADMIN_VIEW_ORG__FAILED = 'ADMIN_VIEW_ORG__FAILED';

export const ADMIN_UPDATE_ORG_REQUESTED = 'ADMIN_UPDATE_ORG_REQUESTED';
export const ADMIN_UPDATE_ORG__SUCCEEDED = 'ADMIN_UPDATE_ORG__SUCCEEDED';
export const ADMIN_UPDATE_ORG__FAILED = 'ADMIN_UPDATE_ORG__FAILED';

export const ADMIN_UPDATE_ORG_STATUS_REQUESTED =
  'ADMIN_UPDATE_ORG_STATUS_REQUESTED';
export const ADMIN_UPDATE_ORG_STATUS__SUCCEEDED =
  'ADMIN_UPDATE_ORG_STATUS__SUCCEEDED';
export const ADMIN_UPDATE_ORG_STATUS__FAILED =
  'ADMIN_UPDATE_STATUS_ORG_STATUS__FAILED';
