export const NAVIGATE_HISTORY_REQUESTED = 'NAVIGATE_HISTORY_REQUESTED';
export const NAVIGATE_HISTORY__SUCCEEDED = 'NAVIGATE_HISTORY__SUCCEEDED';
export const NAVIGATE_HISTORY__FAILED = 'NAVIGATE_HISTORY__FAILED';

export const ALERT_REQUESTED = 'ALERT_REQUESTED';
export const ALERT__SUCCEEDED = 'ALERT__SUCCEEDED';
export const ALERT__FAILED = 'ALERT__FAILED';

export const LOADING_REQUESTED = 'LOADING_REQUESTED';
export const LOADING__SUCCEEDED = 'LOADING__SUCCEEDED';
export const LOADING__FAILED = 'LOADING__FAILED';

export const KEYCLOAK_ROUTE_REQUESTED = 'KEYCLOAK_ROUTE_REQUESTED';
export const KEYCLOAK_ROUTE__SUCCESS = 'KEYCLOAK_ROUTE__SUCCESS';
export const KEYCLOAK_ROUTE__FAILED = 'KEYCLOAK_ROUTE__FAILED';
export const KEYCLOAK_ADMIN_LOGIN = 'KEYCLOAK_ADMIN_LOGIN';
export const KEYCLOAK_ADMIN_LOGOUT = 'KEYCLOAK_ADMIN_LOGOUT';
export const KEYCLOAK_LOGIN = 'KEYCLOAK_LOGIN';
export const KEYCLOAK_LOGOUT = 'KEYCLOAK_LOGOUT';
export const KEYCLOAK_UPDATE = 'KEYCLOAK_UPDATE';
