// PREIVEW
export const EXPERIENCE_PREVIEW_REQUESTED = 'EXPERIENCE_PREVIEW_REQUESTED';
export const EXPERIENCE_PREVIEW__SUCCEEDED = 'EXPERIENCE_PREVIEW__SUCCEEDED';
export const EXPERIENCE_PREVIEW__FAILED = 'EXPERIENCE_PREVIEW__FAILED';

export const EXPERIENCE_PREVIEW_CLOSE_REQUESTED =
  'EXPERIENCE_PREVIEW_CLOSE_REQUESTED';

// CREATE EXPIERENCE
export const EXPERIENCE_INITIAL_REQUESTED = 'EXPERIENCE_INITIAL_REQUESTED';
export const EXPERIENCE_INITIAL__SUCCEEDED = 'EXPERIENCE_INITIAL__SUCCEEDED';
export const EXPERIENCE_INITIAL__FAILED = 'EXPERIENCE_INITIAL__FAILED';

export const EXPERIENCE_CREATE_REQUESTED = 'EXPERIENCE_CREATE_REQUESTED';
export const EXPERIENCE_CREATE__SUCCEEDED = 'EXPERIENCE_CREATE__SUCCEEDED';
export const EXPERIENCE_CREATE__FAILED = 'EXPERIENCE_CREATE__FAILED';

export const EXPERIENCE_UPLOAD_FILE_REQUESTED =
  'EXPERIENCE_UPLOAD_FILE_REQUESTED';
export const EXPERIENCE_UPLOAD_FILE__SUCCEEDED =
  'EXPERIENCE_UPLOAD_FILE__SUCCEEDED';
export const EXPERIENCE_UPLOAD_FILE__FAILED = 'EXPERIENCE_UPLOAD_FILE__FAILED';

export const EXPERIENCE_UPLOAD_GOOGLE_FILE_REQUESTED =
  'EXPERIENCE_UPLOAD_GOOGLE_FILE_REQUESTED';
export const EXPERIENCE_UPLOAD_GOOGLE_FILE__SUCCEEDED =
  'EXPERIENCE_UPLOAD_GOOGLE_FILE__SUCCEEDED';
export const EXPERIENCE_UPLOAD_GOOGLE_FILE__FAILED =
  'EXPERIENCE_UPLOAD_GOOGLE_FILE__FAILED';

export const EXPERIENCE_TYPE_REQUESTED = 'EXPERIENCE_TYPE_REQUESTED';
export const EXPERIENCE_TYPE__SUCCEEDED = 'EXPERIENCE_TYPE__SUCCEEDED';
export const EXPERIENCE_TYPE__FAILED = 'EXPERIENCE_TYPE__FAILED';

export const EXPERIENCE_TYPE_UPDATE_REQUESTED =
  'EXPERIENCE_TYPE_UPDATE_REQUESTED';
export const EXPERIENCE_TYPE_UPDATE__SUCCEEDED =
  'EXPERIENCE_TYPE_UPDATE__SUCCEEDED';
export const EXPERIENCE_TYPE_UPDATE__FAILED = 'EXPERIENCE_TYPE_UPDATE__FAILED';

export const EXPERIENCE_INDEX_UPDATE_REQUESTED =
  'EXPERIENCE_INDEX_UPDATE_REQUESTED';
export const EXPERIENCE_INDEX_UPDATE__SUCCEEDED =
  'EXPERIENCE_INDEX_UPDATE__SUCCEEDED';
export const EXPERIENCE_INDEX_UPDATE__FAILED =
  'EXPERIENCE_INDEX_UPDATE__FAILED';

export const EXPERIENCE_TITLE_UPDATE_REQUESTED =
  'EXPERIENCE_TITLE_UPDATE_REQUESTED';
export const EXPERIENCE_TITLE_UPDATE__SUCCEEDED =
  'EXPERIENCE_TITLE_UPDATE__SUCCEEDED';
export const EXPERIENCE_TITLE_UPDATE__FAILED =
  'EXPERIENCE_TITLE_UPDATE__FAILED';

export const EXPERIENCE_CARD_TEMPLATE_TOGGLE_REQUESTED =
  'EXPERIENCE_CARD_TEMPLATE_TOGGLE_REQUESTED';
export const EXPERIENCE_CARD_TEMPLATE_TOGGLE__SUCCEEDED =
  'EXPERIENCE_CARD_TEMPLATE_TOGGLE__SUCCEEDED';
export const EXPERIENCE_CARD_TEMPLATE_TOGGLE__FAILED =
  'EXPERIENCE_CARD_TEMPLATE_TOGGLE__FAILED';

export const EXPERIENCE_CARD_TEMPLATE_FETCH_REQUESTED =
  'EXPERIENCE_CARD_TEMPLATE_FETCH_REQUESTED';
export const EXPERIENCE_CARD_TEMPLATE_FETCH__SUCCEEDED =
  'EXPERIENCE_CARD_TEMPLATE_FETCH__SUCCEEDED';
export const EXPERIENCE_CARD_TEMPLATE_FETCH__FAILED =
  'EXPERIENCE_CARD_TEMPLATE_FETCH__FAILED';

export const EXPERIENCE_CARD_TEMPLATE_SELECT_REQUESTED =
  'EXPERIENCE_CARD_TEMPLATE_SELECT_REQUESTED';
export const EXPERIENCE_CARD_TEMPLATE_SELECT__SUCCEEDED =
  'EXPERIENCE_CARD_TEMPLATE_SELECT__SUCCEEDED';
export const EXPERIENCE_CARD_TEMPLATE_SELECT__FAILED =
  'EXPERIENCE_CARD_TEMPLATE_SELECT__FAILED';

export const EXPERIENCE_CARD_TEMPLATE_ELEM_SELECT_REQUESTED =
  'EXPERIENCE_CARD_TEMPLATE_ELEM_SELECT_REQUESTED';
export const EXPERIENCE_CARD_TEMPLATE_ELEM_SELECT__SUCCEEDED =
  'EXPERIENCE_CARD_TEMPLATE_ELEM_SELECT__SUCCEEDED';
export const EXPERIENCE_CARD_TEMPLATE_ELEM_SELECT__FAILED =
  'EXPERIENCE_CARD_TEMPLATE_ELEM_SELECT__FAILED';

export const EXPERIENCE_CARD_TEMPLATE_UPDATE_IMAGE_REQUESTED =
  'EXPERIENCE_CARD_TEMPLATE_UPDATE_IMAGE_REQUESTED';
export const EXPERIENCE_CARD_TEMPLATE_UPDATE_IMAGE__SUCCEEDED =
  'EXPERIENCE_CARD_TEMPLATE_UPDATE_IMAGE__SUCCEEDED';
export const EXPERIENCE_CARD_TEMPLATE_UPDATE_IMAGE__FAILED =
  'EXPERIENCE_CARD_TEMPLATE_UPDATE_IMAGE__FAILED';

export const EXPERIENCE_CARD_TEMPLATE_UPDATE_COLOR_REQUESTED =
  'EXPERIENCE_CARD_TEMPLATE_UPDATE_COLOR_REQUESTED';
export const EXPERIENCE_CARD_TEMPLATE_UPDATE_COLOR__SUCCEEDED =
  'EXPERIENCE_CARD_TEMPLATE_UPDATE_COLOR__SUCCEEDED';
export const EXPERIENCE_CARD_TEMPLATE_UPDATE_COLOR__FAILED =
  'EXPERIENCE_CARD_TEMPLATE_UPDATE_COLOR__FAILED';

export const EXPERIENCE_CARD_TEMPLATE_UPDATE_OPACITY_REQUESTED =
  'EXPERIENCE_CARD_TEMPLATE_UPDATE_OPACITY_REQUESTED';
export const EXPERIENCE_CARD_TEMPLATE_UPDATE_OPACITY__SUCCEEDED =
  'EXPERIENCE_CARD_TEMPLATE_UPDATE_OPACITY__SUCCEEDED';
export const EXPERIENCE_CARD_TEMPLATE_UPDATE_OPACITY__FAILED =
  'EXPERIENCE_CARD_TEMPLATE_UPDATE_OPACITY__FAILED';

export const EXPERIENCE_CARD_TEMPLATE_UPDATE_CONTENT_REQUESTED =
  'EXPERIENCE_CARD_TEMPLATE_UPDATE_CONTENT_REQUESTED';
export const EXPERIENCE_CARD_TEMPLATE_UPDATE_CONTENT__SUCCEEDED =
  'EXPERIENCE_CARD_TEMPLATE_UPDATE_CONTENT__SUCCEEDED';
export const EXPERIENCE_CARD_TEMPLATE_UPDATE_CONTENT__FAILED =
  'EXPERIENCE_CARD_TEMPLATE_UPDATE_CONTENT__FAILED';

export const EXPERIENCE_CARD_TEMPLATE_SAVE_REQUESTED =
  'EXPERIENCE_CARD_TEMPLATE_SAVE_REQUESTED';
export const EXPERIENCE_CARD_TEMPLATE_SAVE__SUCCEEDED =
  'EXPERIENCE_CARD_TEMPLATE_SAVE__SUCCEEDED';
export const EXPERIENCE_CARD_TEMPLATE_SAVE__FAILED =
  'EXPERIENCE_CARD_TEMPLATE_SAVE__FAILED';

export const EXPERIENCE_CARD_TEMPLATE_REMOVE_REQUESTED =
  'EXPERIENCE_CARD_TEMPLATE_REMOVE_REQUESTED';
export const EXPERIENCE_CARD_TEMPLATE_REMOVE__SUCCEEDED =
  'EXPERIENCE_CARD_TEMPLATE_REMOVE__SUCCEEDED';
export const EXPERIENCE_CARD_TEMPLATE_REMOVE__FAILED =
  'EXPERIENCE_CARD_TEMPLATE_REMOVE__FAILED';

export const EXPERIENCE_PAGE_PAGES_SAVE_REQUESTED =
  'EXPERIENCE_PAGE_PAGES_SAVE_REQUESTED';
export const EXPERIENCE_PAGE_PAGES_SAVE__SUCCEEDED =
  'EXPERIENCE_PAGE_PAGES_SAVE__SUCCEEDED';
export const EXPERIENCE_PAGE_PAGES_SAVE__FAILED =
  'EXPERIENCE_PAGE_PAGES_SAVE__FAILED';

export const EXPERIENCE_PAGE_PAGES_REMOVE_REQUESTED =
  'EXPERIENCE_PAGE_PAGES_REMOVE_REQUESTED';
export const EXPERIENCE_PAGE_PAGES_REMOVE__SUCCEEDED =
  'EXPERIENCE_PAGE_PAGES_REMOVE__SUCCEEDED';
export const EXPERIENCE_PAGE_PAGES_REMOVE__FAILED =
  'EXPERIENCE_PAGE_PAGES_REMOVE__FAILED';

export const EXPERIENCE_PAGE_SET_ROOT_REQUESTED =
  'EXPERIENCE_PAGE_SET_ROOT_REQUESTED';
export const EXPERIENCE_PAGE_SET_ROOT__SUCCEEDED =
  'EXPERIENCE_PAGE_SET_ROOT__SUCCEEDED';
export const EXPERIENCE_PAGE_SET_ROOT__FAILED =
  'EXPERIENCE_PAGE_SET_ROOT__FAILED';

export const EXPERIENCE_PAGE_DOC_PANEL_TOGGLE_REQUESTED =
  'EXPERIENCE_PAGE_DOC_PANEL_TOGGLE_REQUESTED';
export const EXPERIENCE_PAGE_DOC_PANEL_TOGGLE__SUCCEEDED =
  'EXPERIENCE_PAGE_DOC_PANEL_TOGGLE__SUCCEEDED';
export const EXPERIENCE_PAGE_DOC_PANEL_TOGGLE__FAILED =
  'EXPERIENCE_PAGE_DOC_PANEL_TOGGLE__FAILED';

export const EXPERIENCE_PAGE_TEMPLATE_OPTION_SELECT_REQUESTED =
  'EXPERIENCE_PAGE_TEMPLATE_OPTION_SELECT_REQUESTED';
export const EXPERIENCE_PAGE_TEMPLATE_OPTION_SELECT__SUCCEEDED =
  'EXPERIENCE_PAGE_TEMPLATE_OPTION_SELECT__SUCCEEDED';
export const EXPERIENCE_PAGE_TEMPLATE_OPTION_SELECT__FAILED =
  'EXPERIENCE_PAGE_TEMPLATE_OPTION_SELECT__FAILED';

export const EXPERIENCE_PAGE_TEMPLATE_TOGGLE_REQUESTED =
  'EXPERIENCE_PAGE_TEMPLATE_TOGGLE_REQUESTED';
export const EXPERIENCE_PAGE_TEMPLATE_TOGGLE__SUCCEEDED =
  'EXPERIENCE_PAGE_TEMPLATE_TOGGLE__SUCCEEDED';
export const EXPERIENCE_PAGE_TEMPLATE_TOGGLE__FAILED =
  'EXPERIENCE_PAGE_TEMPLATE_TOGGLE__FAILED';

export const EXPERIENCE_PAGE_TEMPLATE_FETCH_REQUESTED =
  'EXPERIENCE_PAGE_TEMPLATE_FETCH_REQUESTED';
export const EXPERIENCE_PAGE_TEMPLATE_FETCH__SUCCEEDED =
  'EXPERIENCE_PAGE_TEMPLATE_FETCH__SUCCEEDED';
export const EXPERIENCE_PAGE_TEMPLATE_FETCH__FAILED =
  'EXPERIENCE_PAGE_TEMPLATE_FETCH__FAILED';

export const EXPERIENCE_PAGE_CAROUSEL_TOGGLE_REQUESTED =
  'EXPERIENCE_PAGE_CAROUSEL_TOGGLE_REQUESTED';
export const EXPERIENCE_PAGE_CAROUSEL_TOGGLE__SUCCEEDED =
  'EXPERIENCE_PAGE_CAROUSEL_TOGGLE__SUCCEEDED';
export const EXPERIENCE_PAGE_CAROUSEL_TOGGLE__FAILED =
  'EXPERIENCE_PAGE_CAROUSEL_TOGGLE__FAILED';

export const EXPERIENCE_PAGE_CAROUSEL_ACTIVE_REQUESTED =
  'EXPERIENCE_PAGE_CAROUSEL_ACTIVE_REQUESTED';
export const EXPERIENCE_PAGE_CAROUSEL_ACTIVE__SUCCEEDED =
  'EXPERIENCE_PAGE_CAROUSEL_ACTIVE__SUCCEEDED';
export const EXPERIENCE_PAGE_CAROUSEL_ACTIVE__FAILED =
  'EXPERIENCE_PAGE_CAROUSEL_ACTIVE__FAILED';

export const EXPERIENCE_PAGE_ADD_PAGE_REQUESTED =
  'EXPERIENCE_PAGE_ADD_PAGE_REQUESTED';
export const EXPERIENCE_PAGE_ADD_PAGE__SUCCEEDED =
  'EXPERIENCE_PAGE_ADD_PAGE__SUCCEEDED';
export const EXPERIENCE_PAGE_ADD_PAGE__FAILED =
  'EXPERIENCE_PAGE_ADD_PAGE__FAILED';

export const EXPERIENCE_PAGE_DELETE_PAGE_REQUESTED =
  'EXPERIENCE_PAGE_DELETE_PAGE_REQUESTED';
export const EXPERIENCE_PAGE_DELETE_PAGE__SUCCEEDED =
  'EXPERIENCE_PAGE_DELETE_PAGE__SUCCEEDED';
export const EXPERIENCE_PAGE_DELETE_PAGE__FAILED =
  'EXPERIENCE_PAGE_DELETE_PAGE__FAILED';

export const EXPERIENCE_PAGE_ADD_ELEM_REQUESTED =
  'EXPERIENCE_PAGE_ADD_ELEM_REQUESTED';
export const EXPERIENCE_PAGE_ADD_ELEM__SUCCEEDED =
  'EXPERIENCE_PAGE_ADD_ELEM__SUCCEEDED';
export const EXPERIENCE_PAGE_ADD_ELEM__FAILED =
  'EXPERIENCE_PAGE_ADD_ELEM__FAILED';

export const EXPERIENCE_PAGE_DELETE_ELEM_REQUESTED =
  'EXPERIENCE_PAGE_DELETE_ELEM_REQUESTED';
export const EXPERIENCE_PAGE_DELETE_ELEM__SUCCEEDED =
  'EXPERIENCE_PAGE_DELETE_ELEM__SUCCEEDED';
export const EXPERIENCE_PAGE_DELETE_ELEM__FAILED =
  'EXPERIENCE_PAGE_DELETE_ELEM__FAILED';

export const EXPERIENCE_PAGE_COPY_ELEM_REQUESTED =
  'EXPERIENCE_PAGE_COPY_ELEM_REQUESTED';
export const EXPERIENCE_PAGE_COPY_ELEM__SUCCEEDED =
  'EXPERIENCE_PAGE_COPY_ELEM__SUCCEEDED';
export const EXPERIENCE_PAGE_COPY_ELEM__FAILED =
  'EXPERIENCE_PAGE_COPY_ELEM__FAILED';

export const EXPERIENCE_PAGE_SHUFFLE_ELEM_REQUESTED =
  'EXPERIENCE_PAGE_SHUFFLE_ELEM_REQUESTED';
export const EXPERIENCE_PAGE_SHUFFLE_ELEM__SUCCEEDED =
  'EXPERIENCE_PAGE_SHUFFLE_ELEM__SUCCEEDED';
export const EXPERIENCE_PAGE_SHUFFLE_ELEM__FAILED =
  'EXPERIENCE_PAGE_SHUFFLE_ELEM__FAILED';

export const EXPERIENCE_PAGE_SELECT_ELEM_REQUESTED =
  'EXPERIENCE_PAGE_SELECT_ELEM_REQUESTED';
export const EXPERIENCE_PAGE_SELECT_ELEM__SUCCEEDED =
  'EXPERIENCE_PAGE_SELECT_ELEM__SUCCEEDED';
export const EXPERIENCE_PAGE_SELECT_ELEM__FAILED =
  'EXPERIENCE_PAGE_SELECT_ELEM__FAILED';

export const EXPERIENCE_PAGE_SELECT_ELEM_BY_TYPE_REQUESTED =
  'EXPERIENCE_PAGE_SELECT_ELEM_BY_TYPE_REQUESTED';
export const EXPERIENCE_PAGE_SELECT_ELEM_BY_TYPE__SUCCEEDED =
  'EXPERIENCE_PAGE_SELECT_ELEM_BY_TYPE__SUCCEEDED';
export const EXPERIENCE_PAGE_SELECT_ELEM_BY_TYPE__FAILED =
  'EXPERIENCE_PAGE_SELECT_ELEM_BY_TYPE__FAILED';

export const EXPERIENCE_PAGE_UNSELECT_ELEM_BY_TYPE_REQUESTED =
  'EXPERIENCE_PAGE_UNSELECT_ELEM_BY_TYPE_REQUESTED';
export const EXPERIENCE_PAGE_UNSELECT_ELEM_BY_TYPE__SUCCEEDED =
  'EXPERIENCE_PAGE_UNSELECT_ELEM_BY_TYPE__SUCCEEDED';
export const EXPERIENCE_PAGE_UNSELECT_ELEM_BY_TYPE__FAILED =
  'EXPERIENCE_PAGE_UNSELECT_ELEM_BY_TYPE__FAILED';

export const EXPERIENCE_PAGE_UPDATE_ELEM_REQUESTED =
  'EXPERIENCE_PAGE_UPDATE_ELEM_REQUESTED';
export const EXPERIENCE_PAGE_UPDATE_ELEM__SUCCEEDED =
  'EXPERIENCE_PAGE_UPDATE_ELEM__SUCCEEDED';
export const EXPERIENCE_PAGE_UPDATE_ELEM__FAILED =
  'EXPERIENCE_PAGE_UPDATE_ELEM__FAILED';

export const EXPERIENCE_PAGE_ELEM_CONNECT_PAGE_REQUESTED =
  'EXPERIENCE_PAGE_ELEM_CONNECT_PAGE_REQUESTED';
export const EXPERIENCE_PAGE_ELEM_CONNECT_PAGE__SUCCEEDED =
  'EXPERIENCE_PAGE_ELEM_CONNECT_PAGE__SUCCEEDED';
export const EXPERIENCE_PAGE_ELEM_CONNECT_PAGE__FAILED =
  'EXPERIENCE_PAGE_ELEM_CONNECT_PAGE__FAILED';

// UPDATE EXPERIENCE
export const EXPERIENCE_VIEW_REQUESTED = 'EXPERIENCE_VIEW_REQUESTED';
export const EXPERIENCE_VIEW__SUCCEEDED = 'EXPERIENCE_VIEW__SUCCEEDED';
export const EXPERIENCE_VIEW__FAILED = 'EXPERIENCE_VIEW__FAILED';

export const EXPERIENCE_VIEW_HTML_FETCH_REQUESTED =
  'EXPERIENCE_VIEW_HTML_FETCH_REQUESTED';
export const EXPERIENCE_VIEW_HTML_FETCH__SUCCEEDED =
  'EXPERIENCE_VIEW_HTML_FETCH__SUCCEEDED';
export const EXPERIENCE_VIEW_HTML_FETCH__FAILED =
  'EXPERIENCE_VIEW_HTML_FETCH__FAILED';

export const EXPERIENCE_UPDATE_FILE_REQUESTED =
  'EXPERIENCE_UPDATE_FILE_REQUESTED';
export const EXPERIENCE_UPDATE_FILE__SUCCEEDED =
  'EXPERIENCE_UPDATE_FILE__SUCCEEDED';
export const EXPERIENCE_UPDATE_FILE__FAILED = 'EXPERIENCE_UPDATE_FILE__FAILED';

export const EXPERIENCE_UPDATE_REQUESTED = 'EXPERIENCE_UPDATE_REQUESTED';
export const EXPERIENCE_UPDATE__SUCCEEDED = 'EXPERIENCE_UPDATE__SUCCEEDED';
export const EXPERIENCE_UPDATE__FAILED = 'EXPERIENCE_UPDATE__FAILED';
